# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from evervolt.models.inline_object3_inner import InlineObject3Inner

class TestInlineObject3Inner(unittest.TestCase):
    """InlineObject3Inner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineObject3Inner:
        """Test InlineObject3Inner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineObject3Inner`
        """
        model = InlineObject3Inner()
        if include_optional:
            return InlineObject3Inner(
                name = '',
                id = ''
            )
        else:
            return InlineObject3Inner(
        )
        """

    def testInlineObject3Inner(self):
        """Test InlineObject3Inner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
