# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_devices_delete(self) -> None:
        """Test case for devices_delete

        """
        pass

    def test_devices_get(self) -> None:
        """Test case for devices_get

        """
        pass

    def test_devices_post(self) -> None:
        """Test case for devices_post

        """
        pass

    def test_energy_prices_post(self) -> None:
        """Test case for energy_prices_post

        """
        pass

    def test_energy_schedule_post(self) -> None:
        """Test case for energy_schedule_post

        """
        pass

    def test_energy_starttime_post(self) -> None:
        """Test case for energy_starttime_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
