# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from evervolt.models.devices_delete_request import DevicesDeleteRequest

class TestDevicesDeleteRequest(unittest.TestCase):
    """DevicesDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DevicesDeleteRequest:
        """Test DevicesDeleteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DevicesDeleteRequest`
        """
        model = DevicesDeleteRequest()
        if include_optional:
            return DevicesDeleteRequest(
                id = ''
            )
        else:
            return DevicesDeleteRequest(
        )
        """

    def testDevicesDeleteRequest(self):
        """Test DevicesDeleteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
