# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from evervolt.api.devices_api import DevicesApi


class TestDevicesApi(unittest.TestCase):
    """DevicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DevicesApi()

    def tearDown(self) -> None:
        pass

    def test_devices_delete(self) -> None:
        """Test case for devices_delete

        Delete device
        """
        pass

    def test_devices_get(self) -> None:
        """Test case for devices_get

        Get devices
        """
        pass

    def test_devices_post(self) -> None:
        """Test case for devices_post

        Add device
        """
        pass


if __name__ == '__main__':
    unittest.main()
