# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from evervolt.models.providers import Providers

class TestProviders(unittest.TestCase):
    """Providers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviders(self):
        """Test Providers"""
        # inst = Providers()

if __name__ == '__main__':
    unittest.main()
