# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from evervolt.api.prices_api import PricesApi


class TestPricesApi(unittest.TestCase):
    """PricesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PricesApi()

    def tearDown(self) -> None:
        pass

    def test_energy_prices_post(self) -> None:
        """Test case for energy_prices_post

        Electricity prices
        """
        pass

    def test_energy_schedule_post(self) -> None:
        """Test case for energy_schedule_post

        Optimal schedule
        """
        pass

    def test_energy_starttime_post(self) -> None:
        """Test case for energy_starttime_post

        Optimal start time
        """
        pass


if __name__ == '__main__':
    unittest.main()
