# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from evervolt.api.customer_api import CustomerApi


class TestCustomerApi(unittest.TestCase):
    """CustomerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomerApi()

    def tearDown(self) -> None:
        pass

    def test_customer_get(self) -> None:
        """Test case for customer_get

        Get customer
        """
        pass


if __name__ == '__main__':
    unittest.main()
