# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from evervolt.models.inline_object1_inner import InlineObject1Inner

class TestInlineObject1Inner(unittest.TestCase):
    """InlineObject1Inner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineObject1Inner:
        """Test InlineObject1Inner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineObject1Inner`
        """
        model = InlineObject1Inner()
        if include_optional:
            return InlineObject1Inner(
                id = '',
                name = '',
                usage_profile = [
                    evervolt.models.usage_profile_inner.usageProfile_inner(
                        duration = 'PT1H', 
                        usage = 1.337, )
                    ]
            )
        else:
            return InlineObject1Inner(
        )
        """

    def testInlineObject1Inner(self):
        """Test InlineObject1Inner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
