# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from evervolt.models.energy_schedule_post_request import EnergySchedulePostRequest

class TestEnergySchedulePostRequest(unittest.TestCase):
    """EnergySchedulePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnergySchedulePostRequest:
        """Test EnergySchedulePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnergySchedulePostRequest`
        """
        model = EnergySchedulePostRequest()
        if include_optional:
            return EnergySchedulePostRequest(
                start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                splittable_usage = evervolt.models._energy_schedule_post_request_splittable_usage._energy_schedule_post_request_splittableUsage(
                    duration = 'PT1H', 
                    usage = 1.337, )
            )
        else:
            return EnergySchedulePostRequest(
        )
        """

    def testEnergySchedulePostRequest(self):
        """Test EnergySchedulePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
