# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from evervolt.models.usage_profile_inner import UsageProfileInner

class TestUsageProfileInner(unittest.TestCase):
    """UsageProfileInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageProfileInner:
        """Test UsageProfileInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageProfileInner`
        """
        model = UsageProfileInner()
        if include_optional:
            return UsageProfileInner(
                duration = 'PT1H',
                usage = 1.337
            )
        else:
            return UsageProfileInner(
        )
        """

    def testUsageProfileInner(self):
        """Test UsageProfileInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
