openapi: 3.1.0
info:
  title: Evervolt
  description: Evervolt API documentation
  version: 1.0.0
servers:
  - url: https://api.evervolt.beestree.nl
tags:
  - name: devices
    description: Device CRUD operations
    x-displayName: Devices
  - name: prices
    description: Perform calculations based on actual or historic energy prices
    x-displayName: Prices
  - name: other
    description: Other
    x-displayName: Other
paths:
  /devices:
    post:
      summary: Add device
      description: This endpoint is used to add a new device
      tags:
        - devices
      security:
        - ApiKey: []
      requestBody:
        $ref: '#/components/requestBodies/body'
      responses:
        '200':
          $ref: '#/components/responses/response-200-2'
    get:
      summary: Get devices
      description: This endpoint is used to get all devices
      tags:
        - devices
      security:
        - ApiKey: []
      responses:
        '200':
          $ref: '#/components/responses/response-200'
    delete:
      summary: Delete device
      description: This endpoint is used to delete a device
      tags:
        - devices
      security:
        - ApiKey: []
      requestBody:
        $ref: '#/components/requestBodies/body-2'
      responses:
        '200':
          $ref: '#/components/responses/response-200-3'
  /energy/prices:
    post:
      summary: Electricity prices
      description: This endpoint is used to retrieve current or historical electricity prices
      tags:
        - prices
      security:
        - ApiKey: []
      requestBody:
        $ref: '#/components/requestBodies/body-3'
      responses:
        '200':
          $ref: '#/components/responses/response-200-4'
        '404':
          $ref: '#/components/responses/response-404'
  /energy/starttime:
    post:
      summary: Optimal start time
      description: This endpoint is used to calculate the optimal start time for a device based on its usage pattern
      tags:
        - prices
      security:
        - ApiKey: []
      requestBody:
        $ref: '#/components/requestBodies/body-4'
      responses:
        '200':
          $ref: '#/components/responses/response-200-5'
  /energy/schedule:
    post:
      summary: Optimal schedule
      description: This endpoint is used to calculate the optimal schedule for a device based on the electricity prices
      tags:
        - prices
      security:
        - ApiKey: []
      requestBody:
        $ref: '#/components/requestBodies/body-5'
      responses:
        '200':
          $ref: '#/components/responses/response-200-6'
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
  schemas:
    duration:
      type: string
      format: duration
      example: PT1H
    usageProfile:
      type: array
      items:
        type: object
        properties:
          duration:
            $ref: '#/components/schemas/duration'
          usage:
            type: number
            format: float
            description: Usage in kWh for the given duration
    default-start-time:
      type: string
      format: date-time
      description: Defaults to the current time, rounded down to the beginning of the nearest defined interval (e.g., if the interval is 1 hour, it defaults to the last full hour).
    default-end-time:
      type: string
      format: date-time
      description: Defaults to 24 hours in the future, rounded up to the beginning of the nearest defined interval (e.g., if the interval is 1 hour, it defaults to the next full hour).
    providers:
      type: string
      enum:
        - zonneplan
        - frankenergie
      description: '[See all supported providers](/docs/category/aanbieders)'
    schedule-slot:
      type: object
      properties:
        start:
          type: string
          format: date-time
          description: Start time of the slot
        end:
          type: string
          format: date-time
          description: End time of the slot
        price:
          type: number
          format: float
          description: Price per kWh
  responses:
    response-200:
      description: Successfully retrieved devices
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                usageProfile:
                  $ref: '#/components/schemas/usageProfile'
    response-200-2:
      description: Successfully added the new device
    response-200-3:
      description: Successfully deleted the device
    response-200-4:
      description: Successfully retrieved electricity prices
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/schedule-slot'
    response-404:
      description: |
        Electricity prices could not be found due to one of the following reasons:
        - The given provider does not exist ([See all supported providers](/docs/category/aanbieders))
        - No market price data is available for (part of) the requested range
        - No purchasing fee data is available for (part of) the requested range
        - No tax data is available for (part of) the requested range
        - No vat data is available for (part of) the requested range

        The response body will contain more information on the exact reason
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                enum:
                  - ProviderNotFoundException
                  - TermNotAvailableException
              traceId:
                type: string
              message:
                type: string
              details:
                type: object
    response-200-5:
      description: Successfully retrieved optimal starting time
      content:
        application/json:
          schema:
            type: object
            properties:
              start:
                type: string
                format: date-time
                description: Recommended optimal start time
              cost:
                type: number
                format: float
                description: Cost if the device is started at the resulting time
              costNow:
                type: number
                format: float
                description: Cost if the device would be started now
    response-200-6:
      description: Successfully retrieved optimal schedule
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/schedule-slot'
  requestBodies:
    body:
      required: false
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              usageProfile:
                $ref: '#/components/schemas/usageProfile'
    body-2:
      required: false
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
    body-3:
      required: false
      content:
        application/json:
          schema:
            type: object
            properties:
              start:
                $ref: '#/components/schemas/default-start-time'
              end:
                $ref: '#/components/schemas/default-end-time'
              provider:
                $ref: '#/components/schemas/providers'
              includeTax:
                type: boolean
                description: Whether to include tax in the returned prices
    body-4:
      required: false
      content:
        application/json:
          schema:
            type: object
            properties:
              usageProfile:
                $ref: '#/components/schemas/usageProfile'
    body-5:
      required: false
      content:
        application/json:
          schema:
            type: object
            properties:
              start:
                $ref: '#/components/schemas/default-start-time'
              end:
                $ref: '#/components/schemas/default-end-time'
              splittableUsage:
                type: object
                properties:
                  duration:
                    $ref: '#/components/schemas/duration'
                  usage:
                    type: number
                    format: float
                    description: Usage in kW for the given duration
