# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from evervolt.models.energy_schedule_post_request_splittable_usage import EnergySchedulePostRequestSplittableUsage
from typing import Optional, Set
from typing_extensions import Self

class EnergySchedulePostRequest(BaseModel):
    """
    EnergySchedulePostRequest
    """ # noqa: E501
    start: Optional[datetime] = Field(default=None, description="Defaults to the current time, rounded down to the beginning of the nearest defined interval (e.g., if the interval is 1 hour, it defaults to the last full hour).")
    end: Optional[datetime] = Field(default=None, description="Defaults to 24 hours in the future, rounded up to the beginning of the nearest defined interval (e.g., if the interval is 1 hour, it defaults to the next full hour).")
    splittable_usage: Optional[EnergySchedulePostRequestSplittableUsage] = Field(default=None, alias="splittableUsage")
    __properties: ClassVar[List[str]] = ["start", "end", "splittableUsage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnergySchedulePostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of splittable_usage
        if self.splittable_usage:
            _dict['splittableUsage'] = self.splittable_usage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnergySchedulePostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "start": obj.get("start"),
            "end": obj.get("end"),
            "splittableUsage": EnergySchedulePostRequestSplittableUsage.from_dict(obj["splittableUsage"]) if obj.get("splittableUsage") is not None else None
        })
        return _obj


