# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class InlineObject(BaseModel):
    """
    InlineObject
    """ # noqa: E501
    is_subscribed: Optional[StrictBool] = Field(default=None, alias="isSubscribed")
    devices: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of devices the customer has configured")
    api_usage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of API calls made by the customer", alias="apiUsage")
    devices_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Maximum number of devices the customer can configure", alias="devicesLimit")
    api_usage_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Maximum number of API calls the customer can make", alias="apiUsageLimit")
    email: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["isSubscribed", "devices", "apiUsage", "devicesLimit", "apiUsageLimit", "email"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InlineObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InlineObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isSubscribed": obj.get("isSubscribed"),
            "devices": obj.get("devices"),
            "apiUsage": obj.get("apiUsage"),
            "devicesLimit": obj.get("devicesLimit"),
            "apiUsageLimit": obj.get("apiUsageLimit"),
            "email": obj.get("email")
        })
        return _obj


