# coding: utf-8

"""
    Evervolt

    Evervolt API documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Providers(str, Enum):
    """
    [See all supported providers](/docs/category/providers)
    """

    """
    allowed enum values
    """
    MARKET = 'market'
    ZONNEPLAN = 'zonneplan'
    FRANKENERGIE = 'frankenergie'
    TIBBER = 'tibber'
    ANWBENERGIE = 'anwbenergie'
    ENERGYZERO = 'energyzero'
    PUREENERGIE = 'pureenergie'
    ESSENT = 'essent'
    VANDEBRON = 'vandebron'
    VATTENFALL = 'vattenfall'
    ENECO = 'eneco'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Providers from a JSON string"""
        return cls(json.loads(json_str))


